### ISSUE TITLE
Column Mismatch in Admin average fine view

### ISSUE THREAD

**Issue by leobarnabas** [JackQinCh/CS631Lirary#1]
Column header is displayed as , 
ID
Name
Type
Average Fine

However, the contents are ordered as ,
READERID,
RTYPE,
RNAME,
AVGFINE

Please refer the file admin_avg_fine.php, line no from 44 to 56.

![image](https://cloud.githubusercontent.com/assets/15973751/14931436/6c6022c8-0e39-11e6-8ecb-b57ea80d58ec.png)

**Comment by JackQinCh** [comment]
Have fixed it. Thank you!
